# -*- coding: utf-8 -*-
"""Kịch bản gốc — phần 1 (S1..S5). Đổi tên CLARA → MAYA, giữ nguyên 100% câu chữ."""

S1 = ("SCENE 1: ST. MICHAEL'S CHURCH — ALTAR", [
 ("PRIEST", "Dear friends, we are gathered here today to join Maya Bennett and Ryan Prescott in holy marriage."),
 ("GUEST ONE", "The music started twenty-five minutes ago. Where is the groom?"),
 ("MAYA", "He is coming. He is always late. He will be here."),
 ("GUEST TWO", "Sweetheart, sit down. Your hands are shaking."),
 ("MAYA", "I am fine. Please, everyone, just give him five more minutes."),
 ("RYAN", "Stop the music. Stop it. Everyone, be quiet."),
 ("MAYA", "Ryan? Ryan, why are you holding her hand?"),
 ("RYAN", "Father, give me the microphone. I want all two hundred people in this room to hear this clearly."),
 ("PRIEST", "Mr. Prescott, this is the house of God. Please lower your voice."),
 ("RYAN", "I am not marrying her. There. I said it out loud so nobody has to whisper about it later."),
 ("MAYA", "What are you talking about? Ryan, look at me."),
 ("RYAN", "I am looking at you. That is the problem. Look at that dress. It is borrowed. The shoes are borrowed. Even the flowers are from the hospital gift shop."),
 ("MAYA", "You told me you did not care about money."),
 ("RYAN", "I was twenty-four and stupid. I am thirty-one now, Maya. I want a life. I want a future. What is your future? Night shifts, plastic gloves, and a mother rotting in a hospital bed."),
 ("GUEST ONE", "My God. Someone stop him."),
 ("RYAN", "I cannot marry a woman who wipes strangers for a living and has a dying mother attached to her like a debt. Say it with me. I am not marrying a bedpan maid."),
 ("MAYA", "Her name is Helen. She is my mother. Say her name."),
 ("VANESSA", "Oh, honey. Nobody in this room wants to know her name."),
 ("MAYA", "Who are you?"),
 ("VANESSA", "Vanessa Hale. My father owns Hale Group. Ryan works for a company we do business with, and last month he finally learned what a real woman looks like."),
 ("MAYA", "You knew he was getting married today."),
 ("VANESSA", "Of course I knew. That is why I came. I wanted to see the dress."),
 ("RYAN", "Vanessa, do not be cruel."),
 ("VANESSA", "I am not cruel. I am generous. Here. Compensation for the poor girl."),
 ("GUEST TWO", "Did she just throw money at her? In a church?"),
 ("VANESSA", "Pick it up. That is more cash than you make in three months, nurse."),
 ("MAYA", "Eleven thousand. There is eleven thousand dollars here."),
 ("VANESSA", "See? She counted it. They always count it."),
 ("MAYA", "My mother's bill is two hundred thousand. Eleven thousand does not even buy her one more week. Keep it. You need it more than I do."),
 ("VANESSA", "Excuse me?"),
 ("MAYA", "You just paid eleven thousand dollars for a man who left a woman at an altar. That was a very bad price. Keep your money."),
 ("RYAN", "Do not talk to her like that."),
 ("MAYA", "I will not talk to her at all. Father, thank you. Everyone, please go home. There is no wedding."),
 ("VANESSA", "We are done here. Ryan, bring the car around. And somebody move that wheelchair out of the aisle, we cannot get through."),
 ("ADRIAN", "Sorry."),
 ("VANESSA", "Was I talking to you? Push him aside, Ryan. I am not stepping over wheels in this dress."),
 ("RYAN", "Vanessa, just walk around him."),
 ("VANESSA", "I do not walk around people. That is the entire point of being me."),
 ("ADRIAN", "Sebastian."),
 ("SEBASTIAN", "Sir."),
 ("ADRIAN", "Write down every face in this room. Every single one."),
 ("SEBASTIAN", "Including the bride, sir?"),
 ("ADRIAN", "Especially her. But put her name on a different list."),
])

S2 = ("SCENE 2: CHURCH PARKING LOT", [
 ("MAYA", "Hello? Yes, this is Maya Bennett."),
 ("BILLING CLERK", "Miss Bennett, I am calling about your mother, Helen Bennett, ICU bed twelve. I am very sorry to do this today."),
 ("MAYA", "Do what today?"),
 ("BILLING CLERK", "The outstanding balance is two hundred and four thousand dollars. The hospital board has issued a final notice. If payment is not received, life support will be withdrawn Thursday at six in the morning."),
 ("MAYA", "Thursday. That is thirty-one hours."),
 ("BILLING CLERK", "I am truly sorry. I have three children. I hate this job today."),
 ("MAYA", "Please. I work there. I am a nurse in that building. I have worked four hundred night shifts in that building."),
 ("BILLING CLERK", "I know who you are, Miss Bennett. It does not change the number."),
 ("MAYA", "Mrs. Prescott. Mrs. Prescott, please wait. Please roll down the window."),
 ("MRS. PRESCOTT", "What do you want? My son has already humiliated himself enough for one morning."),
 ("MAYA", "Twenty thousand. Not two hundred. Just twenty thousand and I can buy time. I will sign anything. I will work it off for ten years."),
 ("MRS. PRESCOTT", "Get your hand off my car door."),
 ("MAYA", "I am begging you. I have never begged anyone in my life. I am on my knees in a parking lot in a wedding dress. Look at me."),
 ("MRS. PRESCOTT", "I am looking. And do you know what I see? A beggar who almost got into my family."),
 ("MAYA", "My mother is dying."),
 ("MRS. PRESCOTT", "Then let her die like poor people do. Quietly. A beggar does not get to touch the Prescott name."),
 ("MAYA", "My hand. My hand is in the door."),
 ("MRS. PRESCOTT", "Then move it."),
])

S3 = ("SCENE 3: PAWN SHOP AND BANK LOBBY", [
 ("PAWN BROKER", "Gold ring. Thin band. Nineteen seventy-eight, I would guess."),
 ("MAYA", "Nineteen seventy-nine. My mother's wedding ring. She never took it off, not once in forty years, until they put her in the ICU."),
 ("PAWN BROKER", "Eight hundred."),
 ("MAYA", "It is real gold."),
 ("PAWN BROKER", "It is real thin gold. Eight hundred."),
 ("MAYA", "My car is outside. Two thousand two, one hundred sixty thousand miles."),
 ("PAWN BROKER", "I do not buy cars."),
 ("MAYA", "I sold it this morning. Fourteen hundred. I walked here. I just wanted someone to know I tried everything."),
 ("PAWN BROKER", "Lady, you are still wearing a wedding dress."),
 ("MAYA", "I know."),
 ("LOAN OFFICER", "Miss Bennett, this is the third application in eight days."),
 ("MAYA", "I fixed the paperwork. I brought my pay stubs. I brought four years of them."),
 ("LOAN OFFICER", "Your income is fine. Your collateral is zero. You own nothing."),
 ("MAYA", "I own a certification. I am an ICU nurse. That took six years."),
 ("LOAN OFFICER", "The system cannot lend against six years, Miss Bennett. It lends against property."),
 ("MAYA", "Then tell the system that a woman dies Thursday morning at six."),
 ("LOAN OFFICER", "Security will walk you out. Please do not shout in the lobby."),
 ("MAYA", "I am not shouting. I am sitting down. I am just going to sit on this sidewalk for one minute, and then I will figure something out."),
])

S4 = ("SCENE 4: BACK PEW — EMPTY CHURCH", [
 ("MAYA", "Sorry. I did not know anyone was still here. I came back for my mother's coat."),
 ("ADRIAN", "Six hours. You have been gone six hours."),
 ("MAYA", "You have been sitting in an empty church for six hours?"),
 ("ADRIAN", "I had nowhere better to be. Sit down, Miss Bennett."),
 ("MAYA", "How do you know my name?"),
 ("ADRIAN", "A priest said it about forty times this morning."),
 ("MAYA", "Right. Look, whatever you saw today, I would rather not talk about it."),
 ("ADRIAN", "I do not want to talk about it. I want to make you an offer. Read this."),
 ("MAYA", "This is a contract."),
 ("ADRIAN", "Twelve months. You become my legal wife. Separate room, separate bed, no touching. You do not ask about my family. You do not ask about my accident. You do not ask where my money comes from."),
 ("MAYA", "And in exchange?"),
 ("ADRIAN", "Your mother's hospital bill is paid in full within four hours of your signature. Not a loan. Paid. Cleared. Gone."),
 ("MAYA", "Two hundred and four thousand dollars."),
 ("ADRIAN", "Two hundred and four thousand, one hundred and twelve. I like exact numbers."),
 ("MAYA", "Why me?"),
 ("ADRIAN", "Ten minutes before I spoke to you, a rich woman threw cash in your face in front of two hundred people. You had every reason to scream. To cry. To pull her hair. Instead you knelt down and counted it. You stacked the bills straight and you gave them back."),
 ("MAYA", "That is not a good reason to marry someone."),
 ("ADRIAN", "It is the only reason I have ever needed. I am not saving you, Miss Bennett. I am hiring you."),
 ("MAYA", "Everyone will laugh at me. They will say I sold myself to a man in a wheelchair for two hundred thousand dollars."),
 ("ADRIAN", "Yes. They will."),
 ("MAYA", "And that does not bother you?"),
 ("ADRIAN", "I have been laughed at for six months. I have gotten very good at it. Do you want the pen or not?"),
 ("MAYA", "There is no table."),
 ("ADRIAN", "Use the hymn book."),
 ("MAYA", "Maya Bennett. There. I signed my life away on the back of a church hymn book."),
 ("ADRIAN", "Adrian Kane."),
 ("MAYA", "Adrian. If you are lying to me, I will find you."),
 ("ADRIAN", "If I am lying to you, Miss Bennett, I will deserve it."),
])

S5 = ("SCENE 5: ST. AGNES HOSPITAL — BILLING OFFICE, 5:47 AM", [
 ("MAYA", "I need to see a supervisor. Please. My name is Maya Bennett, my mother is Helen Bennett, bed twelve, and the withdrawal order is set for tomorrow morning."),
 ("BILLING CLERK", "Bennett. Let me pull it up."),
 ("MAYA", "I have four thousand two hundred dollars. It is everything I have. I sold my car, I sold her ring. I am asking for two weeks. Just two weeks and I will find the rest."),
 ("BILLING CLERK", "Miss Bennett."),
 ("MAYA", "I will sign a wage assignment. Take my whole paycheck. Take it for five years."),
 ("BILLING CLERK", "Miss Bennett, stop talking and look at the screen."),
 ("MAYA", "What am I looking at?"),
 ("BILLING CLERK", "The balance is zero."),
 ("MAYA", "That is a system error. That happens sometimes at month end."),
 ("BILLING CLERK", "It is not an error. Payment posted at four oh six this morning. Full amount. Wire transfer from a private trust account."),
 ("MAYA", "Which trust?"),
 ("BILLING CLERK", "It just says private client, priority handling. Honey, I have worked this desk eleven years. I have never seen a two hundred thousand dollar bill cleared in one wire at four in the morning."),
 ("MAYA", "And the withdrawal order?"),
 ("BILLING CLERK", "Cancelled. There is a note attached. It says continue all care indefinitely, no cost ceiling, and route all questions away from the patient's daughter."),
 ("MAYA", "Away from me?"),
 ("BILLING CLERK", "Somebody does not want you worrying. Miss Bennett, are you all right? You are standing in the middle of the hallway."),
 ("MAYA", "He was telling the truth. The man in the wheelchair was telling the truth."),
])
