# -*- coding: utf-8 -*-
"""Kịch bản gốc — phần 2 (S6..S12)."""

S6 = ("SCENE 6: CITY HALL — MARRIAGE REGISTRY", [
 ("CLERK", "Do you both understand that this is a legally binding civil marriage under state law?"),
 ("ADRIAN", "Yes."),
 ("MAYA", "Yes."),
 ("CLERK", "Any objection from either party?"),
 ("MAYA", "No."),
 ("CLERK", "Sign here, and here. Congratulations. That is four minutes. I think that is a record."),
 ("MAYA", "Thank you."),
 ("CLERK", "Sir, do you want the certificate mailed or printed?"),
 ("ADRIAN", "Printed. Two copies. My wife keeps one."),
 ("MAYA", "There is a man by the door taking pictures of us."),
 ("ADRIAN", "I know."),
 ("MAYA", "He is not a photographer. He is holding a leather folder. He looks like a lawyer."),
 ("ADRIAN", "He is a lawyer. Sebastian."),
 ("SEBASTIAN", "I have the plate number, sir. Gray sedan, out-of-state tags. I will know who paid him before lunch."),
 ("MAYA", "Who would pay a lawyer to photograph a wedding at city hall?"),
 ("ADRIAN", "Clause three, Miss Bennett."),
 ("MAYA", "Clause three says I do not ask about your family."),
 ("ADRIAN", "Correct."),
 ("MAYA", "It is Mrs. Kane now, technically."),
 ("ADRIAN", "It is. Nine days."),
 ("MAYA", "Nine days until what?"),
 ("ADRIAN", "Clause three."),
 ("MAYA", "You are going to be very annoying to live with."),
 ("ADRIAN", "Almost certainly."),
])

S7 = ("SCENE 7: THE OLD GATEHOUSE — KANE ESTATE", [
 ("MAYA", "That gate. That is the biggest gate I have ever seen. Is that the house?"),
 ("SEBASTIAN", "That is the main house, ma'am. Kane Manor. We are not going there."),
 ("MAYA", "Then where are we going?"),
 ("SEBASTIAN", "Here. The old gatehouse."),
 ("MAYA", "This one? The little one by the service road? The roof is patched with tarp."),
 ("SEBASTIAN", "Yes, ma'am."),
 ("MAYA", "There are three steps to the front door. He is in a wheelchair. There is no ramp."),
 ("SEBASTIAN", "There has never been a ramp."),
 ("MAYA", "How long has he lived here?"),
 ("SEBASTIAN", "Six months. Since the accident. The family moved him out of the main house eleven days after he came out of surgery. This is where they threw him."),
 ("MAYA", "Threw him."),
 ("SEBASTIAN", "Their word, ma'am. Not mine."),
 ("ADRIAN", "Sebastian, that is enough."),
 ("MAYA", "Adrian, is that your family's house up on that hill?"),
 ("ADRIAN", "Clause three."),
 ("MAYA", "I am not asking about your family. I am asking about the steps. Sebastian, do we have plywood?"),
 ("SEBASTIAN", "In the shed, ma'am."),
 ("MAYA", "Then we have a ramp by tonight. Adrian, when did anybody last check your pressure sores?"),
 ("ADRIAN", "I do not know what that is."),
 ("MAYA", "That is the answer, then. Shirt off, please."),
 ("ADRIAN", "Excuse me?"),
 ("MAYA", "I am an ICU nurse and you have been sitting in a chair for six months with nobody turning you. Shirt off. I am not asking about your family. I am asking about your skin."),
 ("ADRIAN", "You are not going to complain about this house."),
 ("MAYA", "The house has a roof and my mother is breathing. I have no complaints today."),
])

S8 = ("SCENE 8: KANE MANOR — FAMILY DINNER", [
 ("JULIAN", "Everyone, quiet down. Quiet. My cousin has finally arrived, and he brought a guest."),
 ("AUNT MARGARET", "Is that the girl from the newspaper? The one in the church?"),
 ("JULIAN", "It certainly is. Adrian, we set a place for you. Right there. The small table by the kitchen door."),
 ("ADRIAN", "By the kitchen."),
 ("JULIAN", "The main table is crowded and your chair is very wide. It is a practical decision, not a personal one."),
 ("AUNT MARGARET", "Julian, do not be unkind."),
 ("JULIAN", "I am being efficient, Aunt Margaret. Now, let us all welcome the new bride. Everybody, this is the nurse who changed shifts and became a wife."),
 ("UNCLE PETER", "How much did he pay you, sweetheart? Everyone here wants to know but nobody will say it."),
 ("MAYA", "Two hundred and four thousand, one hundred twelve dollars."),
 ("UNCLE PETER", "She actually answered."),
 ("MAYA", "You asked. That is my mother's hospital bill. Your relative paid it. Is there another question, or can I sit down?"),
 ("JULIAN", "Bold. I like bold. But you are sitting at the small table with him."),
 ("MAYA", "No."),
 ("JULIAN", "I beg your pardon?"),
 ("MAYA", "Excuse me. Coming through. Move the chairs, please. Thank you. Adrian, right here at the head."),
 ("JULIAN", "That is my seat. I am the acting chairman of this family."),
 ("MAYA", "Acting. That means temporary."),
 ("JULIAN", "Do you have any idea who you are speaking to?"),
 ("MAYA", "A man who put his cousin next to a garbage can. Adrian, do you want the meat cut small or medium?"),
 ("ADRIAN", "Maya."),
 ("MAYA", "Answer the question, please. Small or medium?"),
 ("ADRIAN", "Small."),
 ("MAYA", "Small it is. There. Everybody, look at this table. Nineteen people. Not one of you cut his meat. Not one of you asked if he could reach the water. I have known this man for four days."),
 ("AUNT MARGARET", "Young lady, you do not understand this family."),
 ("MAYA", "I understand a room. I have worked in rooms where people die for six years. And in every one of them, the way you treat the weakest person tells me exactly who you are."),
 ("JULIAN", "Get out of my house."),
 ("MAYA", "He is my husband. His seat is here. We will finish eating first."),
])

S9 = ("SCENE 9: ST. AGNES HOSPITAL — ICU, WARD 4, NIGHT", [
 ("MAYA", "Hi, Mom. It is Tuesday. Vitals look good tonight. Your blood pressure is one eighteen over seventy-two, which is better than mine."),
 ("NURSE DIANE", "Maya. You are on shift in ten minutes."),
 ("MAYA", "I know. I am just turning her."),
 ("NURSE DIANE", "I can do that."),
 ("MAYA", "I want to do it."),
 ("NURSE PAULA", "Diane. Diane, come here. Is that her? Is that the one from the church video?"),
 ("NURSE DIANE", "Paula, keep your voice down. She is right there."),
 ("NURSE PAULA", "Two hundred thousand dollars. That is what I heard. She sold herself to a cripple in a wheelchair for two hundred thousand dollars."),
 ("NURSE DIANE", "Paula."),
 ("NURSE PAULA", "I am not judging. I am saying I would have asked for three hundred."),
 ("MAYA", "Diane, can you hand me the barrier cream?"),
 ("NURSE DIANE", "Maya, you do not have to pretend you did not hear that."),
 ("MAYA", "Barrier cream, please. Left heel is getting red."),
 ("NURSE PAULA", "See? She will not even defend herself. That is how you know it is true."),
 ("MAYA", "Mom, your left heel is getting red. That means they have not been turning you every two hours like the chart says. I will fix it. I always fix it."),
 ("NURSE DIANE", "Maya, your knuckles are white. You are holding her hand too hard."),
 ("MAYA", "Am I?"),
 ("NURSE DIANE", "Let go, honey. Just for a second. Let go."),
])

S10 = ("SCENE 10: SIDEWALK CAFÉ", [
 ("VANESSA", "Ryan. Ryan, stop walking. Look who it is."),
 ("RYAN", "You have got to be kidding me."),
 ("VANESSA", "The bride and her prize. Oh my God, she really does push him around town."),
 ("MAYA", "Adrian, let us go the other way."),
 ("ADRIAN", "No."),
 ("VANESSA", "Maya. Maya Bennett. Or is it Maya Kane now? I read the registry filing. Everybody read it."),
 ("MAYA", "Excuse us. You are standing in front of the ramp."),
 ("RYAN", "Four days. Four days after our wedding you married this. Do you know how that makes me look?"),
 ("MAYA", "It makes you look like a man who ran off with someone else at his own wedding."),
 ("RYAN", "You did this to punish me."),
 ("MAYA", "I did this to keep my mother breathing. Not everything is about you, Ryan."),
 ("VANESSA", "Let me look at him. Stand up, sweetheart. Oh, wait. You cannot."),
 ("ADRIAN", "Move."),
 ("VANESSA", "It talks."),
 ("MAYA", "Do not touch the chair."),
 ("VANESSA", "Oops."),
 ("MAYA", "Adrian. Adrian, are you hurt? Do not move your neck. Look at my finger."),
 ("VANESSA", "Relax, nurse. He fell on the street, not off a building."),
 ("MAYA", "You pushed a wheelchair into traffic."),
 ("VANESSA", "I nudged it. And here, take a coffee. It looks like he spilled some on his legs. Whoops. That is hot. Very hot. But it does not matter, does it? He cannot feel anything down there anyway."),
 ("RYAN", "Vanessa, that is enough."),
 ("VANESSA", "Why? He is not going to feel it, Ryan. That is the whole joke."),
 ("MAYA", "There. That is for his legs."),
 ("VANESSA", "Did you just slap me? On a public street? Ryan, she slapped me."),
 ("RYAN", "Get on the ground."),
 ("MAYA", "Let go of my arm."),
 ("RYAN", "I said get down. You are a nobody, Maya. You have always been a nobody, and today the whole street gets to see it."),
 ("ADRIAN", "Ryan Prescott. Vanessa Hale. Say your names again. Loudly."),
 ("VANESSA", "Why? So you can cry about it later?"),
 ("ADRIAN", "So I remember them correctly."),
 ("VANESSA", "Look at him. Face down on the pavement, giving orders. That is the funniest thing I have seen all year."),
 ("ADRIAN", "Maya. Get up. Do not let them see you on the ground."),
 ("MAYA", "I am up. I am up, Adrian. I am fine."),
 ("ADRIAN", "Good. Now push. Do not look back at them. Push."),
])

S11 = ("SCENE 11: GATEHOUSE BATHROOM — NIGHT", [
 ("MAYA", "Hold still. This is going to sting where the coffee got you."),
 ("ADRIAN", "I cannot feel it."),
 ("MAYA", "You felt it this afternoon. I watched your jaw move."),
 ("ADRIAN", "You watch too closely."),
 ("MAYA", "It is my job. Lift the left leg for me. There. Adrian, these scars."),
 ("ADRIAN", "What about them."),
 ("MAYA", "This is not a car crash pattern. This is fourteen surgical entries. Two rods, six screws, and a plate here at the hip. Somebody very expensive put you back together."),
 ("ADRIAN", "Is that a question?"),
 ("MAYA", "No. This is a question. What is this folder in your drawer?"),
 ("ADRIAN", "You went through my drawer."),
 ("MAYA", "I went for gauze. The folder was on top of the gauze. It is an X-ray envelope, and it is not from a hospital. It says forensic vehicle inspection."),
 ("ADRIAN", "Put it back."),
 ("MAYA", "There is a photograph inside it. A brake line. And the cut on it is clean and straight. Brake lines do not tear straight, Adrian. They fray."),
 ("ADRIAN", "Maya."),
 ("MAYA", "Somebody cut it. Somebody cut your brake line and then everyone put you in a house with no ramp and called you useless."),
 ("ADRIAN", "Clause four."),
 ("MAYA", "Clause four says I do not ask about the accident."),
 ("ADRIAN", "Yes."),
 ("MAYA", "Then I am not asking. I am going to finish your dressings and then I am going to make you eat something, because you have eaten twice today and both times it was coffee."),
 ("ADRIAN", "You are angry."),
 ("MAYA", "I am furious. But not at you. Lift the other leg, please."),
 ("ADRIAN", "Maya."),
 ("MAYA", "Yes?"),
 ("ADRIAN", "Thank you for not asking."),
 ("MAYA", "You are welcome. Now eat."),
])

S12 = ("SCENE 12: A GLASS OFFICE, 40TH FLOOR", [
 ("SEBASTIAN", "Mr. Halloran, do you know why I am in your office?"),
 ("MR. HALLORAN", "I was told a shareholder representative was coming. Nobody told me which one."),
 ("SEBASTIAN", "You have a sales director named Ryan Prescott."),
 ("MR. HALLORAN", "Yes. Mid-level. Decent numbers."),
 ("SEBASTIAN", "He no longer works here."),
 ("MR. HALLORAN", "Sir, I cannot just terminate a director without cause and process."),
 ("SEBASTIAN", "Then find cause and compress the process. You have twenty minutes."),
 ("MR. HALLORAN", "May I ask who is making this request?"),
 ("SEBASTIAN", "No."),
 ("MR. HALLORAN", "Ryan. Ryan, come in and close the door."),
 ("RYAN", "What is going on? Why is HR standing outside?"),
 ("MR. HALLORAN", "Your position has been eliminated. Effective immediately."),
 ("RYAN", "Eliminated? I closed four accounts last quarter."),
 ("MR. HALLORAN", "It is a restructuring decision."),
 ("RYAN", "A restructuring at eleven in the morning on a Wednesday? Who signed it?"),
 ("MR. HALLORAN", "I did."),
 ("RYAN", "You are lying. You are sweating through your shirt. Who is that man in the hallway?"),
 ("MR. HALLORAN", "Please hand your badge to security at the elevator."),
 ("RYAN", "No. I want to see the CEO. I want to see whoever owns this building."),
 ("MR. HALLORAN", "You do not want that, son."),
 ("RYAN", "I am marrying Vanessa Hale in three weeks. Do you understand what that means? Her father owns half this city."),
 ("MR. HALLORAN", "Ryan. Listen to me carefully, because I am about to do you the only favor I can. Whoever owns this building is not somebody her father says no to."),
 ("RYAN", "Then tell me the name."),
 ("MR. HALLORAN", "I do not know it. And I have run this floor for nine years."),
])
