# -*- coding: utf-8 -*-
"""Kịch bản gốc — phần 3 (S13..S19)."""

S13 = ("SCENE 13: KANE HOLDINGS — SITUATION ROOM", [
 ("BOARD MEMBER ONE", "Sir, the eighteen screens are live. All regional heads are standing by."),
 ("ADRIAN", "Report."),
 ("BOARD MEMBER TWO", "Hale Group's revolving credit line sits at four hundred million dollars, held entirely by Kane Bank. Covenant review is open. We can call it at any time with forty-eight hours notice."),
 ("ADRIAN", "Not yet."),
 ("BOARD MEMBER ONE", "Sir, respectfully, they are weak now. If we call it this week they collapse this week."),
 ("ADRIAN", "If I call it this week, it is a business decision. I do not want a business decision. I want it to happen in a room where they are laughing."),
 ("BOARD MEMBER TWO", "Understood, sir."),
 ("SEBASTIAN", "Sir, the courthouse filing."),
 ("ADRIAN", "Read it."),
 ("SEBASTIAN", "Julian Kane has petitioned for legal guardianship over your person and estate. Grounds are permanent incapacity and absence of qualified care. Hearing is in nine days."),
 ("ADRIAN", "Nine days."),
 ("SEBASTIAN", "If he wins, he controls your voting shares, sir. All of them."),
 ("ADRIAN", "Then he will not win. Clear the room, everyone. Out. Sebastian, stay."),
 ("SEBASTIAN", "Sir, do not do this today. Doctor Reyes said four weeks minimum."),
 ("ADRIAN", "Hold the armrest."),
 ("SEBASTIAN", "Sir."),
 ("ADRIAN", "Hold it."),
 ("SEBASTIAN", "One. Two. Three. Four. Sir, sit down. Sit down."),
 ("ADRIAN", "Four seconds."),
 ("SEBASTIAN", "Four seconds is more than yesterday."),
 ("ADRIAN", "Four seconds is not enough to walk across a room."),
 ("SEBASTIAN", "You have nine days, sir."),
 ("ADRIAN", "Then I need nine seconds by then."),
])

S14 = ("SCENE 14: COUNTY COURTHOUSE — GUARDIANSHIP HEARING", [
 ("JUDGE WHITMORE", "We are here on the petition of Julian Kane regarding Adrian Kane. Counsel, proceed."),
 ("JULIAN'S LAWYER", "Your Honor, our position is simple. Adrian Kane sustained catastrophic spinal trauma six months ago. He is non-ambulatory. He lives alone in an unheated outbuilding. He has no professional care, no medical supervision, and no capacity to manage a multi-billion dollar estate."),
 ("JUDGE WHITMORE", "Mr. Julian Kane, do you wish to add anything?"),
 ("JULIAN", "Only that this is painful for our family, Your Honor. We love Adrian. But love means admitting when someone can no longer take care of himself. He recently married a stranger four days after meeting her. That alone should concern this court."),
 ("JUDGE WHITMORE", "Is the wife present?"),
 ("MAYA", "I am here, Your Honor."),
 ("JUDGE WHITMORE", "State your name and occupation."),
 ("MAYA", "Maya Kane. Registered nurse, critical care certified, six years in the intensive care unit at St. Agnes."),
 ("JULIAN'S LAWYER", "Your Honor, we object to testimony from an interested party."),
 ("JUDGE WHITMORE", "Overruled. She is a licensed clinician. Continue."),
 ("MAYA", "Patient is a thirty-four year old male, six months post incomplete spinal injury at T-eleven and T-twelve. He has partial sensation in both legs and measurable motor response in the right quadriceps. His medication list is baclofen ten milligrams three times daily, gabapentin three hundred at night, and a low dose blood thinner. Blood pressure this morning was one twenty-four over eighty. Skin is intact with no pressure ulcers, which after six months is not luck. It is care."),
 ("JUDGE WHITMORE", "You keep records?"),
 ("MAYA", "Twenty-nine days of them, Your Honor. Vitals twice daily, intake, output, range of motion, everything."),
 ("JULIAN'S LAWYER", "Twenty-nine days is not a history."),
 ("MAYA", "You are right. So let me tell you about the five months before I got there. His counsel just told this court that Mr. Kane lives in an unheated building with no ramp. That is true. Would you like to know who owns that building?"),
 ("JULIAN", "Your Honor."),
 ("MAYA", "Julian Kane does. He signed the transfer. I have the county record. This man cut off my husband's heat, took away his ramp, and then came to court and used the cold house as evidence that he cannot take care of himself."),
 ("JULIAN'S LAWYER", "Your Honor, this is inflammatory."),
 ("MAYA", "It is arithmetic. Your Honor, this man does not need a guardian. He needs his family to stop starving him and calling it mercy."),
 ("JUDGE WHITMORE", "The petition is denied. Mr. Julian Kane, I am ordering the heat and the accessibility modifications restored within seventy-two hours. Do not bring this back to my courtroom."),
 ("JULIAN", "Maya. Look at me for a moment."),
 ("MAYA", "I am looking."),
 ("JULIAN", "You just made a very expensive mistake, and you do not even know what it costs yet."),
])

S15 = ("SCENE 15: COURTHOUSE CAR PARK — RAIN", [
 ("ADRIAN", "Maya."),
 ("MAYA", "That is the first time you have used my name."),
 ("ADRIAN", "You memorized my medication schedule."),
 ("MAYA", "I memorize everybody's. It is not romantic. It is just what I do."),
 ("ADRIAN", "You pulled a county property record."),
 ("MAYA", "At two in the morning, yes. Public database. Nine dollars."),
 ("ADRIAN", "The contract does not require any of that."),
 ("MAYA", "I know what the contract requires."),
 ("ADRIAN", "Then why?"),
 ("MAYA", "Because the contract hired me to be your wife. It did not hire me to stand there and watch."),
 ("ADRIAN", "People do watch. Most people watch."),
 ("MAYA", "Then most people are cowards. Adrian, can I say something that violates clause three?"),
 ("ADRIAN", "You may say it. I may not answer."),
 ("MAYA", "Whoever you were before that accident, you scared them. That is why they are doing all of this. People do not build a cage this big for someone harmless."),
 ("ADRIAN", "I am not answering that."),
 ("MAYA", "I did not think you would. It is raining. Let me get the cover over your legs."),
 ("ADRIAN", "Maya."),
 ("MAYA", "Yes?"),
 ("ADRIAN", "Nine days is now three days."),
 ("MAYA", "I still do not know what that means."),
 ("ADRIAN", "You will."),
])

S16 = ("SCENE 16: THE GATEHOUSE — EVICTION", [
 ("SHERIFF'S DEPUTY", "Ma'am, are you Maya Kane?"),
 ("MAYA", "Yes."),
 ("SHERIFF'S DEPUTY", "This is a notice to vacate. You have four hours."),
 ("MAYA", "Four hours? The judge just ordered the heat restored on Monday."),
 ("SHERIFF'S DEPUTY", "The judge ordered heat. He did not order tenancy. The owner has revoked permission to occupy."),
 ("JULIAN", "Hello, Maya."),
 ("MAYA", "Of course you came in person."),
 ("JULIAN", "I did not want to miss it. Effective this morning, Adrian's family allowance is suspended pending an internal review. His household staff is reassigned. His vehicle is repossessed."),
 ("MAYA", "He does not have a vehicle."),
 ("JULIAN", "I mean the chair."),
 ("MAYA", "The power wheelchair is a medical device."),
 ("JULIAN", "The power wheelchair was purchased with family funds and is family property. Boys, take it."),
 ("ADRIAN", "Take it."),
 ("MAYA", "Adrian, no."),
 ("ADRIAN", "Take it, Maya. Let them."),
 ("JULIAN", "Listen to him. He has learned. Here, cousin. There is an old manual chair in the shed. Consider it a gift."),
 ("MAYA", "The left wheel is bent."),
 ("JULIAN", "Then push harder. Oh, Maya, one more thing. The contract you signed. I have a copy. Twelve months, no touching, paid in cash. Any court in this state would call that what it is."),
 ("MAYA", "Call it whatever you want."),
 ("JULIAN", "You can leave right now, you know. Tear it up. Nobody would blame you. Nobody would even remember your name in a month."),
 ("MAYA", "Deputy, does the notice say four hours?"),
 ("SHERIFF'S DEPUTY", "Yes ma'am."),
 ("MAYA", "Then we will be gone in three. Adrian, we are going to Ridge Street. It is one room, forty-one dollars a week, and the water is hot most nights."),
 ("ADRIAN", "You could go."),
 ("MAYA", "I could."),
 ("ADRIAN", "Why not?"),
 ("MAYA", "Because you asked me that question twice today and both times you looked away before I answered. Adrian, look at me. I am putting the bed under the window."),
 ("ADRIAN", "Why the window?"),
 ("MAYA", "Because in the afternoon the sun comes over that building and it lands right there for two hours. You have been in the dark for six months. Two hours is not much, but it is what I have."),
])

S17 = ("SCENE 17: HALE TOWER — BRIDAL SUITE", [
 ("VANESSA", "Send her in. Maya. Come in. Do not stand in the doorway like a delivery."),
 ("MAYA", "Your assistant said this was a job offer."),
 ("VANESSA", "It is. My grandmother is eighty-nine, she has congestive heart failure, and she refuses to miss my wedding. The family wants a private nurse in the room the whole day."),
 ("MAYA", "There are forty agencies in this city."),
 ("VANESSA", "I want you."),
 ("MAYA", "Why."),
 ("VANESSA", "Three thousand dollars for one day. Cash. Do you want it or not?"),
 ("MAYA", "What are the conditions?"),
 ("VANESSA", "You wear the uniform. The white one, the one that looks like a uniform. You do not sit at a table. You stand by the service door in the back and you are available at all times."),
 ("MAYA", "You want me standing in the corner in scrubs at your wedding."),
 ("VANESSA", "I want a qualified nurse present. If that is uncomfortable for you, take the agency job instead."),
 ("RYAN", "Take it, Maya."),
 ("MAYA", "Ryan."),
 ("RYAN", "You should come. Honestly. You should see what a real wedding looks like. Two hundred guests who actually show up. Live television. A dress that is not borrowed."),
 ("MAYA", "It is the same church."),
 ("VANESSA", "What?"),
 ("MAYA", "St. Michael's. You booked St. Michael's."),
 ("VANESSA", "We did. It has beautiful light in the afternoon."),
 ("MAYA", "You booked the church where he left me."),
 ("VANESSA", "Oh, honey. Do not flatter yourself. It is the best venue in the city. You just happened to be there first."),
 ("MAYA", "Three thousand dollars."),
 ("VANESSA", "Three thousand."),
 ("MAYA", "My mother's medication is eleven hundred a month and I lost my second job. Fine. I will take it."),
 ("VANESSA", "Wonderful. Ryan, write it down. The nurse is confirmed."),
 ("RYAN", "She is confirmed."),
 ("VANESSA", "And Maya. Bring the wheelchair man if you want. There is a step at the back door, but I am sure you will manage."),
])

S18 = ("SCENE 18: ST. AGNES HOSPITAL — HR OFFICE", [
 ("HR DIRECTOR", "Maya, sit down. This is not going to be a long meeting."),
 ("MAYA", "I am on shift in twenty minutes."),
 ("HR DIRECTOR", "You are not on shift. Your access has been suspended."),
 ("MAYA", "On what grounds?"),
 ("HR DIRECTOR", "Falsification of patient records. Three charts flagged in an internal audit last night."),
 ("MAYA", "Which charts?"),
 ("HR DIRECTOR", "I am not authorized to discuss specifics."),
 ("MAYA", "I want to see them. Show me one entry with my login on it that is wrong."),
 ("HR DIRECTOR", "Maya."),
 ("MAYA", "You have known me six years. You wrote my recommendation letter. Show me one chart."),
 ("HR DIRECTOR", "I cannot."),
 ("MAYA", "You cannot, or there is nothing to show?"),
 ("HR DIRECTOR", "Did you know that Gerald Hale donated a new cardiac wing to this hospital on Tuesday? Forty million dollars. They announced it at nine in the morning."),
 ("MAYA", "And the audit started Tuesday night."),
 ("HR DIRECTOR", "The audit started Tuesday night."),
 ("MAYA", "So say it out loud. Say the real reason."),
 ("HR DIRECTOR", "I have two kids in college, Maya. I am not going to say it out loud. Security is waiting to walk you out."),
 ("MAYA", "Through the front? There are thirty people in that lobby right now."),
 ("HR DIRECTOR", "I am sorry. It is protocol for terminations involving records."),
 ("NURSE DIANE", "Maya? Maya, what is happening? Why is security holding your badge?"),
 ("MAYA", "Diane, listen to me. Bed twelve. Turn her every two hours, not every four. The left heel is the problem heel. Write it on the board so the night shift sees it."),
 ("NURSE DIANE", "Maya."),
 ("MAYA", "Every two hours, Diane. Please. Promise me."),
 ("NURSE DIANE", "I promise."),
 ("ADRIAN", "You are home early."),
 ("MAYA", "They let me go a little early tonight. Slow shift."),
 ("ADRIAN", "Slow shift."),
 ("MAYA", "Very slow. Are you hungry? I am going to make eggs."),
])

S19 = ("SCENE 19: PARKING GARAGE — LEVEL B2", [
 ("MAYA", "Adrian, the elevator is out. We have to use the ramp on the far side."),
 ("ADRIAN", "Maya. Stop pushing."),
 ("MAYA", "What?"),
 ("ADRIAN", "There are three men standing between the pillars and they have been standing there for four minutes."),
 ("THUG ONE", "Evening."),
 ("MAYA", "We are just going to our car."),
 ("THUG ONE", "You do not have a car. We checked."),
 ("THUG TWO", "Message from a family member. He says the guardianship hearing did not go the way it should have."),
 ("MAYA", "Do not touch that chair."),
 ("THUG ONE", "Down you go."),
 ("ADRIAN", "Maya, stay back."),
 ("THUG TWO", "Look at that. He rolled all the way to the drain."),
 ("THUG ONE", "Hold his hand flat. Flat, I said. Now this is for the courthouse."),
 ("ADRIAN", "Do it. Do not touch her."),
 ("MAYA", "Get off him. Get off him."),
 ("THUG TWO", "Lady, move."),
 ("MAYA", "No. You want his hands, you go through me."),
 ("THUG ONE", "She is not moving."),
 ("THUG TWO", "Then move her."),
 ("MAYA", "My hair. Let go of my hair."),
 ("THUG ONE", "Stay down, nurse."),
 ("MAYA", "Adrian, do not look. Do not look at me."),
 ("ADRIAN", "Maya."),
 ("MAYA", "I am fine. It is one finger. It is just one finger, it is nothing, I can splint it myself."),
 ("THUG ONE", "That is enough. He got the message. Let us go."),
 ("THUG TWO", "Tell your husband the family says hello."),
 ("MAYA", "Adrian. Adrian, can you hear me? Squeeze my hand. Not that hand, the other one."),
 ("ADRIAN", "Sebastian."),
 ("SEBASTIAN", "Sir, I am here. I am ninety seconds out. Sir, are you hurt?"),
 ("ADRIAN", "Sebastian. Bring it all back."),
 ("SEBASTIAN", "Sir, confirm the order."),
 ("ADRIAN", "All of it. Every board seat, every loan, every camera, every lawyer. Bring it all back."),
 ("SEBASTIAN", "And the timing, sir?"),
 ("ADRIAN", "Saturday. At the wedding."),
 ("MAYA", "Adrian, who are you talking to?"),
 ("ADRIAN", "Maya, give me your hand. The broken one."),
 ("MAYA", "It is not that bad."),
 ("ADRIAN", "Give it to me. Look at me. In four days, everything is going to change, and you are going to hate me for a few minutes."),
 ("MAYA", "Why would I hate you?"),
 ("ADRIAN", "Because I could have stopped this a long time ago."),
])
