# -*- coding: utf-8 -*-
"""Kịch bản gốc — phần 4 (S20..S25)."""

S20 = ("SCENE 20: ST. MICHAEL'S CHURCH — WEDDING OF RYAN AND VANESSA", [
 ("WEDDING PLANNER", "Nurse, you are by the service door. Do not move into camera range."),
 ("MAYA", "Understood."),
 ("WEDDING PLANNER", "What is on your hand?"),
 ("MAYA", "A splint."),
 ("WEDDING PLANNER", "Can you take it off? It will show on television."),
 ("MAYA", "The bone is broken. So no."),
 ("GRANDMOTHER HALE", "Young lady. Come here."),
 ("MAYA", "Yes, ma'am. Are you comfortable? Can I raise your feet?"),
 ("GRANDMOTHER HALE", "What is your name?"),
 ("MAYA", "Maya."),
 ("GRANDMOTHER HALE", "Maya, why is a nurse with a broken hand standing at my granddaughter's wedding?"),
 ("MAYA", "Because the medication is eleven hundred a month, ma'am."),
 ("GRANDMOTHER HALE", "Hm. And who is the man in the wheelchair by the pillar?"),
 ("MAYA", "My husband."),
 ("GRANDMOTHER HALE", "Nobody has spoken to him in an hour."),
 ("MAYA", "They rarely do."),
 ("RYAN", "Well. Look at this. She actually came."),
 ("MAYA", "Congratulations, Ryan."),
 ("RYAN", "You are standing in the exact same spot where you were standing that day. Do you know that? Right there by the third pillar."),
 ("MAYA", "I know."),
 ("RYAN", "I did you a favor, Maya. Look at this room. Live television. Four hundred guests. Senators. You could never have given me this."),
 ("MAYA", "You are right. I could not."),
 ("JULIAN", "Gerald, do you see who is in the corner? My cousin."),
 ("GERALD HALE", "The cripple? At my daughter's wedding?"),
 ("JULIAN", "The nurse works the event. He comes as baggage."),
 ("GERALD HALE", "Well. As long as he stays by the wall."),
])

S21 = ("SCENE 21: THE FRAME-UP", [
 ("VANESSA", "Stop the music. Stop it, everyone."),
 ("GERALD HALE", "Sweetheart, what is wrong?"),
 ("VANESSA", "My necklace. It is gone. The Hale diamond. Two million dollars, Daddy, it was on the vanity ten minutes ago."),
 ("GERALD HALE", "Lock the doors. Nobody leaves this church."),
 ("SECURITY CHIEF", "Sir, we can search the staff."),
 ("VANESSA", "Start with the nurse."),
 ("MAYA", "I have been standing by the service door for two hours. Forty people have seen me."),
 ("VANESSA", "Then you will not mind, will you?"),
 ("SECURITY CHIEF", "Ma'am, open your bag."),
 ("MAYA", "Here."),
 ("SECURITY CHIEF", "Sir. It is here. It was in the side pocket."),
 ("GUEST ONE", "Oh my God. She stole it."),
 ("GERALD HALE", "A thief. At my daughter's wedding. In front of a television camera."),
 ("RYAN", "Maya. Maya, how could you?"),
 ("MAYA", "Ryan, you know me."),
 ("RYAN", "I thought I did. Cameras, are you getting this? Get closer. Everyone should see this."),
 ("VANESSA", "On your knees."),
 ("MAYA", "No."),
 ("VANESSA", "I said get on your knees and apologize to every person in this church."),
 ("MAYA", "I did not take it."),
 ("GERALD HALE", "The necklace was in your bag."),
 ("MAYA", "Somebody put it there."),
 ("VANESSA", "Oh, of course. The poor little nurse was framed. Ryan, hold her arm."),
 ("MAYA", "Let go of my sleeve. You are tearing it."),
 ("RYAN", "Then kneel and it stops."),
 ("MAYA", "I am not going to apologize for something I did not do. I have never apologized for something I did not do in my life and I am not starting in this church."),
 ("VANESSA", "Then I will help you."),
 ("MAYA", "My hand. That is my hand."),
 ("VANESSA", "I know. I can feel the splint under my heel. Down. Thieves belong on the floor."),
 ("GRANDMOTHER HALE", "Vanessa. Vanessa, stop this. Get off that girl."),
 ("VANESSA", "Grandmother, sit down."),
 ("ADRIAN", "Get away from my wife."),
 ("GERALD HALE", "Who let this thing in here?"),
 ("ADRIAN", "I said get away from her."),
 ("GERALD HALE", "You want to say that again, from down there?"),
 ("ADRIAN", "I will say it as many times as you need."),
 ("GERALD HALE", "Then here. Let me help you say it."),
 ("GUEST TWO", "He kicked the chair over. He kicked a disabled man out of his chair."),
 ("JULIAN", "Look at him. Face down on the marble at a black tie wedding. Somebody get a photograph. This is the Kane family legacy, ladies and gentlemen."),
 ("VANESSA", "The thief and the cripple. What a beautiful couple."),
 ("MAYA", "Adrian. Adrian, do not try to get up. Wait for me. I am coming."),
 ("ADRIAN", "No."),
 ("MAYA", "What?"),
 ("ADRIAN", "Stay where you are, Maya. It is time."),
])

S22 = ("SCENE 22: HE STANDS", [
 ("GUEST ONE", "What is he doing?"),
 ("GUEST TWO", "He is pushing off the floor."),
 ("JULIAN", "Sit down, Adrian. You are embarrassing yourself."),
 ("GUEST ONE", "He is on one knee."),
 ("GUEST TWO", "My God. He is standing."),
 ("MAYA", "Adrian."),
 ("JULIAN", "Sit down. Sit down right now."),
 ("ADRIAN", "One step. Two. It is a long room, Julian. Be patient."),
 ("GERALD HALE", "This is a trick. This is some kind of insurance fraud."),
 ("ADRIAN", "Maya. Take my hand. Stand up."),
 ("MAYA", "You can walk."),
 ("ADRIAN", "Not well. Not far. But far enough to reach you. Here. Put my jacket over your shoulders. They tore your sleeve."),
 ("MAYA", "How long?"),
 ("ADRIAN", "Three weeks. Four seconds at first. Then nine. Then thirty."),
 ("MAYA", "You let them push you out of that chair on the sidewalk. You let them."),
 ("ADRIAN", "I needed the names, and men only show you who they are when they think you cannot stand up."),
 ("SECURITY CHIEF", "Sir, the front doors are opening."),
 ("GERALD HALE", "Who are those men? There are twenty of them."),
 ("SEBASTIAN", "Good evening. Nobody leaves the building. Secure the exits."),
 ("GERALD HALE", "You cannot secure my church."),
 ("SEBASTIAN", "It is not your church, Mr. Hale. The diocese sold this property eleven years ago."),
 ("JULIAN", "Sebastian, whatever he is paying you, I will triple it."),
 ("SEBASTIAN", "Chairman. Your coat."),
 ("JULIAN", "What did you call him?"),
 ("BOARD CHAIRMAN CRANE", "Move aside, please. Excuse me. Excuse me."),
 ("GERALD HALE", "That is Crane. That is the chairman of the board of Kane Holdings."),
 ("BOARD CHAIRMAN CRANE", "Sir. The full board is present as instructed."),
 ("ADRIAN", "Good evening, Crane."),
 ("BOARD CHAIRMAN CRANE", "Good evening, Chairman Kane."),
 ("VANESSA", "Chairman."),
 ("GERALD HALE", "No. No, that is impossible. Adrian Kane is in a hospital. Adrian Kane has been incapacitated for six months."),
 ("ADRIAN", "Adrian Kane has been in a wheelchair for six months. Nobody ever asked him a single question. They just talked in front of him."),
 ("MAYA", "Adrian. Adrian, who are you?"),
 ("ADRIAN", "I own Kane Holdings, Maya. All of it. I have owned it since I was twenty-nine."),
 ("MAYA", "Kane Holdings owns St. Agnes Hospital."),
 ("ADRIAN", "Yes."),
 ("MAYA", "My mother's hospital."),
 ("ADRIAN", "Yes."),
 ("MAYA", "The bank that holds Hale Group. The building Ryan worked in."),
 ("ADRIAN", "Yes and yes."),
 ("MAYA", "And you let me push you through this city while people spat on you."),
 ("ADRIAN", "I did."),
 ("MAYA", "Why?"),
 ("ADRIAN", "Because I needed to know if one single person on this earth would be decent to a man who could give them nothing. Twenty-nine days, Maya. You never once knew, and you never once flinched."),
])

S23 = ("SCENE 23: THE HAMMER", [
 ("ADRIAN", "Sebastian. The screen."),
 ("SEBASTIAN", "Yes, sir. House lights down. Playing security footage, bridal suite, camera four, time stamped seven forty-one this evening."),
 ("GUEST ONE", "That is the bride."),
 ("GUEST TWO", "That is Vanessa holding the necklace."),
 ("GUEST ONE", "She is putting it in the nurse's bag. She is putting it in herself."),
 ("VANESSA", "Turn it off. Daddy, make them turn it off."),
 ("ADRIAN", "Play it again. Slower."),
 ("GERALD HALE", "Vanessa. Vanessa, what did you do?"),
 ("VANESSA", "It was a joke. It was a joke, it was going to be funny."),
 ("ADRIAN", "Officer, that is a felony under state law. Filing a false report and criminal defamation on live television. Arrest her."),
 ("POLICE OFFICER", "Miss Hale, hands behind your back."),
 ("VANESSA", "Do not touch me. Do you know who my father is?"),
 ("POLICE OFFICER", "Yes ma'am. Everyone is about to."),
 ("ADRIAN", "Crane."),
 ("BOARD CHAIRMAN CRANE", "Sir."),
 ("ADRIAN", "Kane Bank holds the Hale Group revolving facility. Four hundred million dollars."),
 ("BOARD CHAIRMAN CRANE", "Four hundred and six, sir, with accrued interest."),
 ("ADRIAN", "Call it."),
 ("BOARD CHAIRMAN CRANE", "Calling the full facility. Effective immediately, all Hale Group accounts are frozen pending settlement."),
 ("GERALD HALE", "You cannot. We have three hundred employees."),
 ("ADRIAN", "You had them."),
 ("GERALD HALE", "I will be bankrupt by Monday."),
 ("ADRIAN", "You will be bankrupt by midnight. You kicked a man out of a wheelchair forty minutes ago and four hundred people watched you do it. Get up off the floor, Mr. Hale. Your knees are going to hurt later."),
 ("JULIAN", "Adrian. Adrian, cousin, listen. Whatever you think happened, we can talk about it privately. Family talks privately."),
 ("ADRIAN", "Detective."),
 ("DETECTIVE MOORE", "Julian Kane, you are under arrest for attempted murder, conspiracy, and aggravated assault."),
 ("JULIAN", "Attempted murder? That is insane. That was a car accident."),
 ("DETECTIVE MOORE", "We have the forensic inspection report on the brake line. Clean cut, not a fracture. We have the mechanic who did it. He gave a statement four hours ago."),
 ("JULIAN", "He is lying."),
 ("DETECTIVE MOORE", "We also have eleven minutes of audio of you negotiating the price. Nine thousand dollars, sir. That is what you thought your cousin was worth."),
 ("JULIAN", "Adrian. Adrian, please. We grew up together."),
 ("ADRIAN", "We did. I remembered that every day for six months. It is the only reason I waited this long."),
 ("GUEST ONE", "Somebody should say something. Nobody is saying anything."),
 ("ADRIAN", "Then let me. All of you, look at this woman. You spat on her. You called her a maid, a beggar, a thief. You broke her hand at a wedding while a camera was running."),
 ("GUEST TWO", "Sir, we did not know who you were."),
 ("ADRIAN", "That is the whole problem. You needed to know who I was before you would be decent. You humiliated my wife for four weeks. It took me four minutes to end all of you."),
])

S24 = ("SCENE 24: CHURCH STEPS — AFTERMATH", [
 ("REPORTER", "Miss Hale, do you have a statement? Miss Hale, is it true the necklace was planted?"),
 ("VANESSA", "Get that camera out of my face. Do not film the handcuffs. Do not film the handcuffs."),
 ("REPORTER", "Mr. Hale, sir, is Hale Group insolvent as of tonight?"),
 ("GERALD HALE", "No comment. No comment."),
 ("RYAN", "Maya. Maya, wait. Please."),
 ("MAYA", "Let go of my dress."),
 ("RYAN", "Just one second. One second, that is all I am asking."),
 ("MAYA", "You are on the ground."),
 ("RYAN", "I know. I know I am. Maya, I made a mistake. One mistake. I was weak, and she was rich, and I was stupid for eight weeks. Eight weeks against four years."),
 ("MAYA", "You told two hundred people my mother was rotting."),
 ("RYAN", "I did not mean it."),
 ("MAYA", "You practiced it. You had a microphone in your hand and you told them to say it with you."),
 ("RYAN", "Tell him to stop it. That is all. Just tell your husband to stop the bank. My name is on those accounts too. I signed things, Maya. I will go to prison for things I did not even read."),
 ("MAYA", "Stand up, Ryan."),
 ("RYAN", "What?"),
 ("MAYA", "I am not going to talk to a man on his knees. I know what that feels like. Stand up."),
 ("RYAN", "I am up. I am up. Please."),
 ("MAYA", "Here."),
 ("RYAN", "What is that?"),
 ("MAYA", "Eleven thousand dollars. She threw it at my face in that doorway right there. I never spent a dollar of it."),
 ("RYAN", "You kept it? For four weeks?"),
 ("MAYA", "I kept it because I wanted to give it back on the right day. Take it. You need it more than I do."),
 ("RYAN", "Maya. Maya, look at me."),
 ("MAYA", "No. That part is finished. Adrian, are you all right? You are shaking."),
 ("ADRIAN", "I have been standing for fifty minutes. That is forty-nine minutes longer than any doctor said I could."),
 ("MAYA", "Then lean on me."),
 ("ADRIAN", "I will fall on you."),
 ("MAYA", "Then we will both go down, and I will get us both back up. Lean on me."),
])

S25 = ("SCENE 25: ST. AGNES HOSPITAL — ICU, BED 12", [
 ("NURSE DIANE", "Maya. Maya, come quick. Bed twelve."),
 ("MAYA", "What happened? Is it her pressure?"),
 ("NURSE DIANE", "She opened her eyes. Eleven minutes ago. She is tracking. She squeezed my hand twice."),
 ("MAYA", "Mom. Mom, it is me. It is Maya."),
 ("HELEN", "Maya."),
 ("MAYA", "Do not talk. Just breathe. Small breaths, that is it."),
 ("HELEN", "How long?"),
 ("MAYA", "Seven months, Mom."),
 ("HELEN", "Who paid?"),
 ("MAYA", "A man paid. A stranger paid."),
 ("HELEN", "Strangers do not pay."),
 ("ADRIAN", "This one did, Mrs. Bennett."),
 ("MAYA", "Adrian. You walked all the way up here."),
 ("ADRIAN", "Fourth floor. Sixty-one steps. I counted."),
 ("HELEN", "Who are you?"),
 ("ADRIAN", "My name is Adrian Kane. I married your daughter, and I have two things to give her, and I would like you to be awake when I do it."),
 ("MAYA", "What are those?"),
 ("ADRIAN", "This is the contract. Twelve months, separate rooms, no questions. It is torn in half. It ended tonight."),
 ("MAYA", "And the second thing?"),
 ("ADRIAN", "A name plate. It is an old one, from the foot of a bed."),
 ("MAYA", "It says unidentified. Bed twelve."),
 ("ADRIAN", "Six months before your wedding, a man was brought into this unit with no wallet, no phone, and a spine broken in two places. His family had already told the press he was dead so the share price would settle. For nine days he had no name."),
 ("MAYA", "Bed twelve. That is this bed."),
 ("ADRIAN", "This bed. And every night at two in the morning a night shift nurse turned him, and cleaned him, and talked to him about the weather even though he never answered."),
 ("MAYA", "I do not remember."),
 ("ADRIAN", "You would not. You had four hundred patients that year. But you called me sir. Nine nights, and you never once called me the bed, or the injury, or the case. You said, good evening, sir."),
 ("MAYA", "That is all?"),
 ("ADRIAN", "That is everything. Do you understand now? I did not come to that church on your wedding day to marry you, Maya. I came to say thank you and go home. I sat in the back row with a check in my pocket for a nurse whose name I finally learned from a hospital roster."),
 ("MAYA", "And then Ryan walked in."),
 ("ADRIAN", "And then Ryan walked in."),
 ("MAYA", "Adrian, what are you doing? Your legs."),
 ("ADRIAN", "Give me a second. It is one knee. I can manage one knee."),
 ("HELEN", "Maya. Maya, he is on the floor."),
 ("MAYA", "He is not on the floor, Mom. He is kneeling."),
 ("ADRIAN", "Maya Bennett. I bought a year of your life with money because I did not think anybody would give it to me for free. That was the most arrogant thing I have ever done, and I am sorry. So I am asking properly this time, on my own two legs, in front of your mother, with nothing to offer you that you cannot walk away from."),
 ("MAYA", "You are the richest man in this state."),
 ("ADRIAN", "Not in this room. In this room I am bed twelve. Marry me, Maya."),
 ("MAYA", "There is no contract this time?"),
 ("ADRIAN", "There is no contract. There is no clause three. Ask me anything you want for the rest of your life."),
 ("MAYA", "Then I have one question."),
 ("ADRIAN", "Ask it."),
 ("MAYA", "Are your legs going to hold you until I say yes?"),
 ("ADRIAN", "For that? They will hold."),
 ("MAYA", "Then yes."),
 ("HELEN", "Maya."),
 ("MAYA", "Yes, Mom?"),
 ("HELEN", "Help the boy up."),
])
