# -*- coding: utf-8 -*-
"""Nhận diện ngắn (dùng cho khối `Nhận diện` của prompt video) + cặp REF theo trạng thái."""

# ── nhận diện: mô tả tuổi · sắc tộc · quần áo, KHÔNG tả lại ngũ quan ──
ND = {
 "MAYA_CUOI":   "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, váy cưới satin trắng ngà đi mượn",
 "MAYA_THUONG": "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, áo len xám than bạc màu và quần jean",
 "MAYA_TUTE":   "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, váy suông xanh navy và blazer cùng màu",
 "MAYA_SCRUB":  "phụ nữ da đen 27 tuổi, tóc búi gọn, bộ scrub y tá xanh mòng két",
 "MAYA_TRANG":  "phụ nữ da đen 27 tuổi, tóc búi gọn, đồng phục điều dưỡng trắng, hai ngón tay phải bó nẹp nhôm",
 "MAYA_KHOAC":  "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, áo khoác dạ ngắn màu ô liu bạc và quần jean đen",
 "MAYA_CARO":   "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, sơ mi flannel kẻ caro nâu đỏ và quần jean xanh",
 "MAYA_ONHA":   "phụ nữ da đen 27 tuổi, tóc xoăn XOÃ NGANG VAI, áo nỉ dài tay màu be và quần jogger xám",
 "MAYA_DEN":    "phụ nữ da đen 27 tuổi, tóc xoăn búi cao, váy liền thân màu đen trơn và khăn choàng xám",
 "MAYA_CARDIGAN":"phụ nữ da đen 27 tuổi, tóc xoăn búi cao, cardigan len màu ngà và váy chữ A xám nhạt",
 "MAYA_SCRUBKHOAC":"phụ nữ da đen 27 tuổi, tóc búi gọn, scrub y tá xanh mòng két khoác cardigan len xám dài",
 "ADRIAN_NHATHO":  "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, áo khoác dạ xám than, ngồi xe lăn điện đen",
 "ADRIAN_TUTE":    "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, sơ mi xanh xám và cardigan xám, ngồi xe lăn điện đen",
 "ADRIAN_NHA":     "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, áo thun dài tay xám tro, ngồi xe lăn điện đen",
 "ADRIAN_VESTNGOI":"đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, vest đen cà vạt bạc, ngồi xe lăn điện đen",
 "ADRIAN_XANHREU": "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, áo len xanh rêu, ngồi xe lăn điện đen",
 "ADRIAN_XELANTAY":"đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, áo len xanh rêu, ngồi xe lăn tay cũ khung thép xám",
 "ADRIAN_TIEC":    "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, vest đen cà vạt đen, ngồi xe lăn tay cũ khung thép xám",
 "ADRIAN_VEST":    "đàn ông da đen 34 tuổi, râu quai nón tỉa gọn, vest đen cà vạt đen, ĐỨNG trên hai chân",
 "RYAN_CUOI":   "đàn ông da trắng 31 tuổi, tóc nâu chải ngược, vest ba mảnh xanh navy cài hoa hồng trắng",
 "RYAN_COMLE":  "đàn ông da trắng 31 tuổi, tóc nâu chải ngược, vest xám than không cà vạt",
 "RYAN_TUXEDO": "đàn ông da trắng 31 tuổi, tóc nâu chải ngược, tuxedo đen nơ đen cài hoa hồng trắng",
 "RYAN_ADO":    "đàn ông da trắng 31 tuổi, tóc nâu chải ngược, bomber da lộn nâu hạt dẻ và quần chinos be",
 "RYAN_SOMI":   "đàn ông da trắng 31 tuổi, tóc nâu chải ngược, sơ mi trắng xắn tay và quần âu xanh navy",
 "RYAN_TUXEDOROI":"đàn ông da trắng 31 tuổi, tóc nâu xổ rối, tuxedo đen nơ tháo lủng lẳng, hai đầu gối quần lấm bụi",
 "VANESSA_DO":    "phụ nữ da trắng 28 tuổi, tóc vàng bạch kim dài thẳng, váy lụa đỏ rượu vang",
 "VANESSA_NGAY":  "phụ nữ da trắng 28 tuổi, tóc vàng bạch kim dài thẳng, áo khoác dạ kem và quần âu kem",
 "VANESSA_CODAU": "phụ nữ da trắng 28 tuổi, tóc vàng bạch kim búi cao, váy cưới ren trắng xoè lớn",
 "VANESSA_LUA":   "phụ nữ da trắng 28 tuổi, tóc vàng bạch kim dài thẳng, áo choàng lụa champagne dài",
 "VANESSA_CODAUXO":"phụ nữ da trắng 28 tuổi, tóc vàng bạch kim búi cao đã xổ vài lọn, váy cưới ren trắng xoè lớn",
 "VANESSA_CODAUBAN":"phụ nữ da trắng 28 tuổi, tóc vàng bạch kim xoã rối, váy cưới ren trắng lấm bụi, hai tay còng sau lưng",
 "HELEN":      "phụ nữ da đen 56 tuổi, tóc bạc ngắn, áo bệnh nhân xanh phấn, nằm giường bệnh",
 "SEBASTIAN":  "đàn ông da đen 52 tuổi, đầu cạo trọc, đeo kính, vest đen cà vạt xám than",
 "JULIAN":     "đàn ông da đen 41 tuổi, ria mép mỏng, vest ba mảnh xanh navy",
 "JULIAN_TUX": "đàn ông da đen 41 tuổi, ria mép mỏng, tuxedo đen nơ đen",
 "PRIEST":     "đàn ông da trắng 64 tuổi, tóc bạc thưa, áo lễ trắng ngà và dải stola trắng viền vàng",
 "MRS. PRESCOTT": "phụ nữ da trắng 59 tuổi, tóc vàng tro cắt bob, áo khoác tweed kem cúc vàng",
 "BILLING CLERK": "phụ nữ da trắng 46 tuổi, tóc nâu buộc đuôi ngựa, kính đen bản to, áo blouse xanh nhạt",
 "PAWN BROKER":  "đàn ông da trắng 57 tuổi, râu xám lởm chởm, áo flannel ca rô xám xanh xắn tay",
 "LOAN OFFICER": "đàn ông da trắng 38 tuổi, tóc nâu nhạt, kính gọng trong, sơ mi trắng cà vạt navy",
 "CLERK":        "phụ nữ da đen 51 tuổi, tóc tết búi sau gáy, kính đọc gọng đỏ, blazer xanh navy",
 "AUNT MARGARET":"phụ nữ da đen 66 tuổi, tóc bạc uốn ngắn, áo lụa tím nhạt và áo len kem",
 "UNCLE PETER":  "đàn ông da đen 63 tuổi, ria mép muối tiêu, vest xám than sơ mi hồng",
 "NURSE DIANE":  "phụ nữ da trắng 44 tuổi, tóc đỏ nâu búi thấp, scrub y tá xanh mòng két",
 "NURSE PAULA":  "phụ nữ da trắng 33 tuổi, tóc nâu vàng buộc đuôi ngựa cao, scrub y tá tím hoa cà",
 "MR. HALLORAN": "đàn ông da trắng 56 tuổi, tóc bạc muối tiêu, sơ mi trắng cà vạt navy nới lỏng",
 "BOARD MEMBER ONE": "đàn ông da trắng 49 tuổi, tóc nâu cắt ngắn, vest xanh than cà vạt xám bạc",
 "BOARD MEMBER TWO": "phụ nữ da đen 45 tuổi, tóc bob thẳng ngang cằm, blazer đen sơ mi lụa trắng",
 "JUDGE WHITMORE":   "phụ nữ da đen 61 tuổi, tóc xoăn bạc ngắn, kính đọc, áo choàng thẩm phán đen",
 "JULIAN'S LAWYER":  "đàn ông da trắng 50 tuổi, tóc đen chải bóng, kính tròn đồi mồi, vest xám sọc mảnh",
 "SHERIFF'S DEPUTY": "đàn ông da trắng 36 tuổi, tóc cua vàng sẫm, đồng phục cảnh sát hạt xanh rêu và mũ lưỡi trai",
 "HR DIRECTOR":      "phụ nữ da đen 53 tuổi, tóc búi thấp, kính gọng vàng, blazer xám sơ mi trắng",
 "THUG ONE":         "đàn ông da trắng 38 tuổi, tóc cắt cực ngắn, áo bomber dù đen và găng tay da đen",
 "THUG TWO":         "đàn ông da trắng 32 tuổi, tóc buộc túm nhỏ, hoodie xám than và găng tay da đen",
 "WEDDING PLANNER":  "phụ nữ da trắng 35 tuổi, tóc bob nâu sẫm, tai nghe headset, vest đen ôm",
 "GRANDMOTHER HALE": "phụ nữ da trắng 89 tuổi, tóc bạc uốn phồng, áo lụa xanh phấn, ngồi xe lăn nhẹ khung nhôm bạc",
 "GERALD HALE":      "đàn ông da trắng 62 tuổi, tóc bạc dày chải ngược, tuxedo đen nơ đen",
 "SECURITY CHIEF":   "đàn ông da đen 47 tuổi, đầu cạo trọc, vest đen bó và tai nghe xoắn dây",
 "POLICE OFFICER":   "phụ nữ da đen 31 tuổi, tóc tết búi chặt, đồng phục cảnh sát xanh đen và gilê chống đạn",
 "DETECTIVE MOORE":  "đàn ông da trắng 54 tuổi, tóc xám cắt ngắn, măng tô len xám than",
 "BOARD CHAIRMAN CRANE": "đàn ông da trắng 67 tuổi, tóc bạc thưa, kính gọng vàng, smoking đen nơ đen",
 "REPORTER":         "phụ nữ da trắng 29 tuổi, tóc nâu dài thẳng, áo khoác dạ đỏ tươi, cầm micro đen",
 "GUEST1_COMLE":  "đàn ông da trắng 57 tuổi, tóc bạc muối tiêu, kính gọng mảnh, vest xám bạc",
 "GUEST1_TUX":    "đàn ông da trắng 57 tuổi, tóc bạc muối tiêu, kính gọng mảnh, tuxedo đen nơ đen",
 "GUEST2_LUA":    "phụ nữ da đen 51 tuổi, tóc xoăn ngắn phồng, áo lụa xanh cổ vịt",
 "GUEST2_DAHOI":  "phụ nữ da đen 51 tuổi, tóc xoăn ngắn phồng, váy nhung dài xanh đêm",
}

# ── cặp ref ảnh (portrait + full) theo trạng thái ──
C = {
 "MAYA_CUOI":   ["REF_MAYA_PORTRAIT", "REF_MAYA_CUOI_FULL"],
 "MAYA_THUONG": ["REF_MAYA_PORTRAIT", "REF_MAYA_THUONG_FULL"],
 "MAYA_TUTE":   ["REF_MAYA_PORTRAIT", "REF_MAYA_TUTE_FULL"],
 "MAYA_SCRUB":  ["REF_MAYA_PORTRAIT", "REF_MAYA_SCRUB_FULL"],
 "MAYA_TRANG":  ["REF_MAYA_PORTRAIT", "REF_MAYA_TRANG_FULL"],
 "MAYA_KHOAC":  ["REF_MAYA_PORTRAIT", "REF_MAYA_KHOAC_FULL"],
 "MAYA_CARO":   ["REF_MAYA_PORTRAIT", "REF_MAYA_CARO_FULL"],
 "MAYA_ONHA":   ["REF_MAYA_PORTRAIT", "REF_MAYA_ONHA_FULL"],
 "MAYA_DEN":    ["REF_MAYA_PORTRAIT", "REF_MAYA_DEN_FULL"],
 "MAYA_CARDIGAN":["REF_MAYA_PORTRAIT", "REF_MAYA_CARDIGAN_FULL"],
 "MAYA_SCRUBKHOAC":["REF_MAYA_PORTRAIT", "REF_MAYA_SCRUBKHOAC_FULL"],
 "ADRIAN_NHATHO":   ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_NHATHO_FULL"],
 "ADRIAN_TUTE":     ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_TUTE_FULL"],
 "ADRIAN_NHA":      ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_NHA_FULL"],
 "ADRIAN_VESTNGOI": ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_VESTNGOI_FULL"],
 "ADRIAN_XANHREU":  ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_XANHREU_FULL"],
 "ADRIAN_XELANTAY": ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_XELANTAY_FULL"],
 "ADRIAN_TIEC":     ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_TIEC_FULL"],
 "ADRIAN_VEST":     ["REF_ADRIAN_PORTRAIT", "REF_ADRIAN_VEST_FULL"],
 "RYAN_CUOI":   ["REF_RYAN_PORTRAIT", "REF_RYAN_CUOI_FULL"],
 "RYAN_COMLE":  ["REF_RYAN_PORTRAIT", "REF_RYAN_COMLE_FULL"],
 "RYAN_TUXEDO": ["REF_RYAN_PORTRAIT", "REF_RYAN_TUXEDO_FULL"],
 "RYAN_ADO":    ["REF_RYAN_PORTRAIT", "REF_RYAN_ADO_FULL"],
 "RYAN_SOMI":   ["REF_RYAN_PORTRAIT", "REF_RYAN_SOMI_FULL"],
 "RYAN_TUXEDOROI":["REF_RYAN_PORTRAIT", "REF_RYAN_TUXEDOROI_FULL"],
 "VANESSA_DO":    ["REF_VANESSA_PORTRAIT", "REF_VANESSA_DO_FULL"],
 "VANESSA_NGAY":  ["REF_VANESSA_PORTRAIT", "REF_VANESSA_NGAY_FULL"],
 "VANESSA_CODAU": ["REF_VANESSA_PORTRAIT", "REF_VANESSA_CODAU_FULL"],
 "VANESSA_LUA":   ["REF_VANESSA_PORTRAIT", "REF_VANESSA_LUA_FULL"],
 "VANESSA_CODAUXO":["REF_VANESSA_PORTRAIT", "REF_VANESSA_CODAUXO_FULL"],
 "VANESSA_CODAUBAN":["REF_VANESSA_PORTRAIT", "REF_VANESSA_CODAUBAN_FULL"],
 "HELEN":      ["REF_HELEN_PORTRAIT", "REF_HELEN_ICU_FULL"],
 "SEBASTIAN":  ["REF_SEBASTIAN_PORTRAIT", "REF_SEBASTIAN_VEST_FULL"],
 "JULIAN":     ["REF_JULIAN_PORTRAIT", "REF_JULIAN_VEST_FULL"],
 "JULIAN_TUX": ["REF_JULIAN_PORTRAIT", "REF_JULIAN_TUXEDO_FULL"],
 "PRIEST":     ["REF_PRIEST_PORTRAIT", "REF_PRIEST_AO_FULL"],
 "MRS. PRESCOTT": ["REF_PRESCOTT_PORTRAIT", "REF_PRESCOTT_FULL"],
 "BILLING CLERK": ["REF_CLERKBILL_PORTRAIT", "REF_CLERKBILL_FULL"],
 "PAWN BROKER":  ["REF_PAWN_PORTRAIT", "REF_PAWN_FULL"],
 "LOAN OFFICER": ["REF_LOAN_PORTRAIT", "REF_LOAN_FULL"],
 "CLERK":        ["REF_CLERK_PORTRAIT", "REF_CLERK_FULL"],
 "AUNT MARGARET":["REF_MARGARET_PORTRAIT", "REF_MARGARET_FULL"],
 "UNCLE PETER":  ["REF_PETER_PORTRAIT", "REF_PETER_FULL"],
 "NURSE DIANE":  ["REF_DIANE_PORTRAIT", "REF_DIANE_FULL"],
 "NURSE PAULA":  ["REF_PAULA_PORTRAIT", "REF_PAULA_FULL"],
 "MR. HALLORAN": ["REF_HALLORAN_PORTRAIT", "REF_HALLORAN_FULL"],
 "BOARD MEMBER ONE": ["REF_BOARD1_PORTRAIT", "REF_BOARD1_FULL"],
 "BOARD MEMBER TWO": ["REF_BOARD2_PORTRAIT", "REF_BOARD2_FULL"],
 "JUDGE WHITMORE":   ["REF_WHITMORE_PORTRAIT", "REF_WHITMORE_FULL"],
 "JULIAN'S LAWYER":  ["REF_LAWYER_PORTRAIT", "REF_LAWYER_FULL"],
 "SHERIFF'S DEPUTY": ["REF_DEPUTY_PORTRAIT", "REF_DEPUTY_FULL"],
 "HR DIRECTOR":      ["REF_HR_PORTRAIT", "REF_HR_FULL"],
 "THUG ONE":         ["REF_THUG1_PORTRAIT", "REF_THUG1_FULL"],
 "THUG TWO":         ["REF_THUG2_PORTRAIT", "REF_THUG2_FULL"],
 "WEDDING PLANNER":  ["REF_PLANNER_PORTRAIT", "REF_PLANNER_FULL"],
 "GRANDMOTHER HALE": ["REF_GRANDMA_PORTRAIT", "REF_GRANDMA_FULL"],
 "GERALD HALE":      ["REF_GERALD_PORTRAIT", "REF_GERALD_TUXEDO_FULL"],
 "SECURITY CHIEF":   ["REF_SECURITY_PORTRAIT", "REF_SECURITY_FULL"],
 "POLICE OFFICER":   ["REF_OFFICER_PORTRAIT", "REF_OFFICER_FULL"],
 "DETECTIVE MOORE":  ["REF_MOORE_PORTRAIT", "REF_MOORE_FULL"],
 "BOARD CHAIRMAN CRANE": ["REF_CRANE_PORTRAIT", "REF_CRANE_FULL"],
 "REPORTER":         ["REF_REPORTER_PORTRAIT", "REF_REPORTER_FULL"],
 "GUEST1_COMLE": ["REF_GUEST1_PORTRAIT", "REF_GUEST1_COMLE_FULL"],
 "GUEST1_TUX":   ["REF_GUEST1_PORTRAIT", "REF_GUEST1_TUXEDO_FULL"],
 "GUEST2_LUA":   ["REF_GUEST2_PORTRAIT", "REF_GUEST2_AOLUA_FULL"],
 "GUEST2_DAHOI": ["REF_GUEST2_PORTRAIT", "REF_GUEST2_DAHOI_FULL"],

 # đạo cụ (mỗi thẻ một ảnh)
 "PROP_TIEN":        ["REF_PROP_TIEN"],
 "PROP_HOPDONG":     ["REF_PROP_HOPDONG"],
 "PROP_HOPDONGRACH": ["REF_PROP_HOPDONGRACH"],
 "PROP_NHAN":        ["REF_PROP_NHAN"],
 "PROP_HOSO":        ["REF_PROP_HOSO"],
 "PROP_VONGCO":      ["REF_PROP_VONGCO"],
 "PROP_THONGBAO":    ["REF_PROP_THONGBAO"],
 "PROP_BIENTEN":     ["REF_PROP_BIENTEN"],
}


def refs(*keys):
    out = []
    for k in keys:
        out += C[k]
    return out


def nd(*pairs):
    """[(tên hiển thị, khoá ND)] → danh sách cho khối Nhận diện."""
    return [(t, ND[k]) for t, k in pairs]
